
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.C_Card
{
public sealed partial class CardConfig : Luban.BeanBase
{
    public CardConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Gold = _buf.ReadInt();
        Solt = _buf.ReadInt();
        Desc = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Specialeffects = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Specialeffects.Add(_e0);}}
        Resilience = _buf.ReadInt();
        Defense = _buf.ReadInt();
        Attack = _buf.ReadInt();
        Cardtypeenmu = _buf.ReadInt();
        Cardtypedesc = _buf.ReadString();
        Icon = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Effect = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Effect.Add(_e0);}}
    }

    public static CardConfig DeserializeCardConfig(ByteBuf _buf)
    {
        return new C_Card.CardConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 牌的名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 牌的价值
    /// </summary>
    public readonly int Gold;
    /// <summary>
    /// 卡牌等级
    /// </summary>
    public readonly int Solt;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 附加特殊效果
    /// </summary>
    public readonly System.Collections.Generic.List<int> Specialeffects;
    /// <summary>
    /// 回复力
    /// </summary>
    public readonly int Resilience;
    /// <summary>
    /// 防御力
    /// </summary>
    public readonly int Defense;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 牌类型枚举
    /// </summary>
    public readonly int Cardtypeenmu;
    /// <summary>
    /// 牌类型描述
    /// </summary>
    public readonly string Cardtypedesc;
    /// <summary>
    /// 牌icon
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 牌效果列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> Effect;
   
    public const int __ID__ = 1709341716;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "gold:" + Gold + ","
        + "solt:" + Solt + ","
        + "desc:" + Desc + ","
        + "specialeffects:" + Luban.StringUtil.CollectionToString(Specialeffects) + ","
        + "resilience:" + Resilience + ","
        + "defense:" + Defense + ","
        + "attack:" + Attack + ","
        + "cardtypeenmu:" + Cardtypeenmu + ","
        + "cardtypedesc:" + Cardtypedesc + ","
        + "icon:" + Icon + ","
        + "effect:" + Luban.StringUtil.CollectionToString(Effect) + ","
        + "}";
    }
}
}

