
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.C_Card
{
public partial class LubanCardConfig
{
    private readonly System.Collections.Generic.Dictionary<int, C_Card.CardConfig> _dataMap;
    private readonly System.Collections.Generic.List<C_Card.CardConfig> _dataList;
    
    public LubanCardConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, C_Card.CardConfig>(n);
        _dataList = new System.Collections.Generic.List<C_Card.CardConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            C_Card.CardConfig _v;
            _v = global::GameConfig.C_Card.CardConfig.DeserializeCardConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, C_Card.CardConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<C_Card.CardConfig> DataList => _dataList;

    public C_Card.CardConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public C_Card.CardConfig Get(int key) => _dataMap[key];
    public C_Card.CardConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

